openapi: 3.0.0
info:
  title: SebsApi
  description: >-
    This is the API for the Sebs application.  It is a RESTful API that uses
    JSON as its data format.
  version: '2.0.0'
servers:
  - url: http://my-json-server.typicode.com/sebastienlevert/kiota-api
    description: Demo API
paths:
  /posts:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postList'
components:
  schemas:
    postList:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: '#/components/schemas/post'
    post:
      type: object
      properties:
        userId:
          type: integer
        id:
          type: integer
        title:
          type: string
        body:
          type: string

